[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lwk_wollet = { version = "0.2.0" }
lwk_signer = { version = "0.2.0" }
lwk_common = { version = "0.2.0" }
elements = "0.24.0"